# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SmartParking;encrypt=true;trustServerCertificate=true
# spring.datasource.username=sa
# spring.datasource.password=12345
# spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# server.port=5000


spring.application.name=sps

# Server
server.port=5000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Database (SUPABASE DIRECT)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.qgfcpyrdlucbpvcxrwrn
spring.datasource.password=sps-cnpm-252
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP config:
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

# Swagger
springdoc.swagger-ui.path=/swagger-ui/index.html

# JWT
jwt.token-expiration=86400
jwt.refresh-token-expiration=864000
jwt.secret-key=SmartParkingSystemSecretKey2026123456789

